### ISSUE TITLE
Plans to add Sum-of-Absolute Differences (SAD) method? 

### ISSUE THREAD

**Issue by Somayeh-h** [stschubert/VPR_Tutorial#10]
Hi @stschubert, 

Is it possible if you could please also add the Sum-of-Absolute Differences [1] VPR method? 

[1] Milford, M.J. and Wyeth, G.F., 2012, May. SeqSLAM: Visual route-based navigation for sunny summer days and stormy winter nights. In 2012 IEEE international conference on robotics and automation (pp. 1643-1649). IEEE.

Thanks,
Somayeh

**Comment by stschubert** [comment]
Hi @Somayeh-h,

Nice to hear from you. Sure, I added an implementation of the SAD "descriptor" (grayscale, sampled, patch-normalized images) and the corresponding distance metric (the actual sum of absolute differences).

I'm looking forward to your feedback after testing it.

Best,
Stefan

**Comment by Somayeh-h** [comment]
Hi @stschubert, 

Thank you so much for your quick integration of SAD to the repo. Yes, I can confirm it works as expected. 

Thanks,
Somayeh

**Comment by Somayeh-h** [comment]
Hi @stschubert,

Thank you so much for your quick integration of SAD to the repo. Yes, I can confirm it works as expected.

Thanks,
Somayeh
