### ISSUE TITLE
Any idea to build with GPU versions?

### ISSUE THREAD

**Issue by changh95** [stschubert/VPR_Tutorial#11]
Before I begin - Thanks for making a great repository! Very helpful in learning VPR.

The instructions to build this repository (which is as below), only manages to build CPU version. I wish to run the algorithms in GPU to get a glimpse of the runtime of the descriptors, but I'm struggling to sort out the dependencies. I tried to switch torch and tensorflow to pytorch-cuda and tensorflow-gpu, but conda and mamba solver fails to resolve the environment. Can anyone give me some guidance? 

`mamba create -n vprtutorial python numpy pytorch torchvision natsort tqdm opencv pillow scikit-learn faiss matplotlib-base tensorflow tensorflow-hub tqdm scikit-image patchnetvlad -c conda-forge -c tobiasrobotics`

**Comment by stschubert** [comment]
Hi @changh95,

I'm happy to hear that our repository helps you to learn about VPR.

Our repository already uses GPU support, and you can simply create the conda environment as described [in our readme](https://github.com/stschubert/VPR_Tutorial#requirements). There is no need to switch *tensorflow* to *tensorflow-gpu* because ["tensorflow and tensorflow-gpu have been the same package since TensorFlow 2.1"](https://pypi.org/project/tensorflow-gpu/), and also with torch there is no need to modify something as [installing torch is sufficient for GPU support](https://pytorch.org/get-started/locally/). Instead, please ensure that all GPU drivers are installed properly. 

Please note that I've actually tested our descriptors with GPU support after your request to ensure that everything works well.

**Comment by changh95** [comment]
I tried clean build again, with the docker setting below. I checked nvidia-docker 2 is installed with my system, and NVIDIA driver was installed in my host system too.

When I run the demo.py with PatchNetVLAD, it runs with CPU again. 

Is there something I'm doing wrong? I'm quite new to DL and setting docker system for DL as well - any tips and supports will be greatly appreicated!

```
# CUDA 11.7, TensorRT 8.4.1
FROM nvcr.io/nvidia/tensorrt:22.07-py3 

ARG DEBIAN_FRONTEND=noninteractive

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

RUN conda update -n base conda &&\
    conda install -n base conda-libmamba-solver &&\
    conda config --set solver libmamba

RUN git clone https://github.com/stschubert/VPR_Tutorial.git

RUN conda create -y -n vprtutorial python numpy pytorch torchvision natsort tqdm opencv pillow scikit-learn faiss matplotlib-base tensorflow tensorflow-hub tqdm scikit-image patchnetvlad -c conda-forge -c tobiasrobotics

RUN cd VPR_Tutorial &&\
    pip3 install --no-deps -e .
    
RUN apt-get -y update 
    
RUN apt-get install -y mesa-utils && \
    apt-get install -y libgl1-mesa-glx && \
    apt-get install -y libglu1-mesa-dev && \
    apt-get install -y libglew-dev &&\
    apt-get install -y libglvnd-dev &&\
    apt-get install -y libgl1-mesa-dev &&\
    apt-get install -y libegl1-mesa-dev &&\
    apt-get install -y mesa-common-dev
    ```

**Comment by Tobias-Fischer** [comment]
Hi @changh95 - could you please provide the output of `conda list` after creating your environment? Have you tried creating the environment without Docker? For me, when I try to create an environment, it contains the following packages:
```
...
  + cuda-version                                  11.8  h70ddcb2_2                   conda-forge/noarch       Cached
  + cudatoolkit                                 11.8.0  h4ba93d1_12                  conda-forge/linux-64     Cached
  + cudnn                                    8.8.0.121  h838ba91_3                   conda-forge/linux-64     Cached
...
  + python                                      3.11.6  hab00c5b_0_cpython           conda-forge/linux-64       31MB
  + python-dateutil                              2.8.2  pyhd8ed1ab_0                 conda-forge/noarch       Cached
  + python-flatbuffers                         23.5.26  pyhd8ed1ab_0                 conda-forge/noarch         34kB
  + python_abi                                    3.11  4_cp311                      conda-forge/linux-64        6kB
  + pytorch                                      2.0.0  cuda112py311h13fee9e_200     conda-forge/linux-64     Cached
...
  + tensorboard                                 2.13.0  pyhd8ed1ab_0                 conda-forge/noarch          5MB
  + tensorboard-data-server                      0.7.0  py311h63ff55d_1              conda-forge/linux-64        5MB
  + tensorflow                                  2.13.1  cuda118py311h878bca4_1       conda-forge/linux-64       35kB
  + tensorflow-base                             2.13.1  cuda118py311h002e3ce_1       conda-forge/linux-64      484MB
  + tensorflow-estimator                        2.13.1  cuda118py311h4a64c31_1       conda-forge/linux-64      710kB
  + tensorflow-hub                              0.14.0  pyha3310fb_0                 conda-forge/noarch         69kB
...
  + torchvision                                 0.15.2  cuda112py311h13eef27_4       conda-forge/linux-64       12MB
```

So definitely the GPU versions are being installed. I would recommend trying without Docker first.

**Comment by changh95** [comment]
For me, I don't see cudnn and cuda-version.

```
...
cryptography              41.0.5          py311h63ff55d_0    conda-forge
cudatoolkit               11.8.0              h4ba93d1_12    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
...
python                    3.11.6          hab00c5b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-flatbuffers        23.5.26            pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytorch                   2.0.0           cpu_mkl_py311hd1ebf82_101    conda-forge
...
tensorboard               2.13.0             pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.7.0           py311h63ff55d_1    conda-forge
tensorflow                2.13.1          cpu_py311h4b67847_1    conda-forge
tensorflow-base           2.13.1          cpu_py311ha0be21f_1    conda-forge
tensorflow-estimator      2.13.1          cpu_py311ha26c8b9_1    conda-forge
tensorflow-hub            0.14.0             pyha3310fb_0    conda-forge
...
torchvision               0.15.2          cpu_py311h38ab453_4    conda-forge
```


I'll try building the docker image with pre-installed CUDA and cudnn

**Comment by Tobias-Fischer** [comment]
Have you tried without Docker?

**Comment by Tobias-Fischer** [comment]
Actually, can you try `CONDA_OVERRIDE_CUDA="11.8" mamba create -y -n vprtutorial python numpy pytorch torchvision natsort tqdm opencv pillow scikit-learn faiss matplotlib-base tensorflow tensorflow-hub tqdm scikit-image patchnetvlad -c conda-forge`

**Comment by changh95** [comment]
Thank you so much! It works now :)

![image](https://github.com/stschubert/VPR_Tutorial/assets/39010111/4b75aba5-dbdf-4d65-899f-fc5890bca33c)

**Comment by changh95** [comment]
Thank you again for making a great code repository!

I've recently made a lecture on 'Computer Vision, LiDAR processing, and Sensor Fusion for Autonomous Driving' and released the code exercises in [this repository](https://github.com/changh95/fastcampus_slam_codes) - and I referred to this repository when explaining learning-based place recognition methods. So far, I have a few hundred students who's watching this lecture series - I hope this will help getting your code out there to more computer vision practioners :+1:

**Comment by Tobias-Fischer** [comment]
That’s  great, thanks a lot! Also good to you got it working now. Let us know if there is anything that we can improve.
